### ISSUE TITLE
Locus Maps Classic cannot be selected

### ISSUE THREAD

**Issue by UlliH1** [cgeo/WhereYouGo#402] opened 2022-10-02 15:44 UTC
I'm using WhereYouGO_2022.01.14 on an Android 12 device.
I have installed Locus Maps Classic 3.63.0.

In the settings I selected Locus map.
But when I try to open the map in a Wherigo, it redirects me to Locus Map 4 in the Google Play Store. I don't see any possibility to open the map.

On my old device (Android 8, WhereYouGo_2020.08.21, Locus Map Pro 3.57.1) it worked without problems.

**Comment by SammysHP** [comment] 2022-10-02 18:46
Duplicate of #357.

**Closed by SammysHP** 2022-10-02 18:46 UTC
