### ISSUE TITLE
Add Mapsforge map v4/5 support

### ISSUE THREAD

**Issue by andrixnet** [cgeo/WhereYouGo#390] opened 2022-05-07 19:02 UTC
### Tell us your idea!

At this time WhereYouGo (at least 2022.01.14) apparently only supports Mapsforge v3 map files. 

That is I fed it v4 and v5 maps and it was unable to use them. I tried several versions (from different times) of romania.map, so it's not the fault of a single file.

### What solution would you suggest?

I know c:geo supports v4 and v5 already. Please add support to WhereYouGo as well. 

### Additional Information

Please note that at least considering the maps available at https://download.mapsforge.org/maps/
the newest v3 maps are from 2018, while v4 and v5 are 2022 level.

**Comment by Lineflyer** [comment] 2022-05-07 19:09
Duplicate of #73.
Sadly not much activity/helpers around here. :(

**Closed by Lineflyer** 2022-05-07 19:09 UTC
Labels: Feature Request, Unverified
