### ISSUE TITLE
Menu items too dark

### ISSUE THREAD

**Issue by andrixnet** [cgeo/WhereYouGo#389] opened 2022-05-07 18:55 UTC
### Describe your problem!

Opening the menu on the map view yields a very dark background menu with items in black.

According to my phone (Samsung S9+) I'm using light theme.
Couldn't find any light/dark theme setting. 

Settings section is shown fine.

### How to reproduce?

- Open WhereYouGo
- Open Map.
- click either on hamburger menu or click on location icon (both on top bar)

### Actual result after these steps?

![Screenshot_20220226-112403_WhereYouGo](https://user-images.githubusercontent.com/3382777/167267977-fa14c40c-0be0-42f8-a14b-1ccce41fa4ec.jpg)

### Expected result after these steps?

I'd expect the menu to be themed in a readable way. Ie. high contrast between menu background and menu item colors

### Reproducible

Yes

### WhereYouGo Version

2022.01.14

### System information

```text
Samsung S9+, SM-G965F, Android-9
```

**Comment by bekuno** [comment] 2022-05-08 21:33
This is a duplicate of #66.
It seems like a Samsung specific problem.

**Closed by bekuno** 2022-05-08 21:33 UTC
Labels: Bug, Duplicate
