### ISSUE TITLE
Avoid typically problems with login/download (missing credentials)

### ISSUE THREAD

**Issue by CachingFoX** [cgeo/WhereYouGo#24] opened 2020-01-15 07:50 UTC
For a normal cgeo/Whereyougo user it is not always clear that Whereyougo is a separate application with own settings and the credentials for www.geocaching.com/www.wherigo.com have to be entered again.
The fact is the reason for problems with login and downlaod of cartridges. 
Many times people have problems with the login and download  and ask for a solution in forum and facebook groups. The most reason for the problem is missing credentials in Whereyougo.

Solution: Give the user an annoucement if credentials are missing and open (the settings) a dialog for enterring the credentials.

**Comment by SchoolGuy** [comment] 2020-01-15 08:16
That is done by me and so a duplicate of https://github.com/cgeo/WhereYouGo/issues/11

**Closed** 2020-01-15 14:38 UTC
